services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # backend
  server:
    build: ./server
    container_name: server_container
    ports:
      - "5000:5000"
    volumes:
    - ./server:/app
    - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  # frontend
  client:
    build: ./client
    container_name: client_container
    ports:
      - "5173:5173"
    volumes:
    - ./client:/app
    - /app/node_modules
    depends_on:
    - server

volumes:
  mongo-data: