import dotenv from "dotenv";
dotenv.config();

const ENV_CONFIG = {
  //   CLOUDINARY
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_FOLDER_NAME: process.env.CLOUDINARY_FOLDER_NAME,
  CLOUDINARY_PRESET: process.env.CLOUDINARY_PRESET,

  //   MONGODB
  MONGODB_URI: process.env.MONGODB_URI,
  MONGODB_DB_NAME: process.env.MONGODB_DB_NAME,
  MONGODB_USER: process.env.MONGODB_USER,
  MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
  MONGODB_PORT: process.env.MONGODB_PORT,
  MONGODB_HOST: process.env.MONGODB_HOST,

  //   REDIS
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_DB: process.env.REDIS_DB,

  //   JWT
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  JWT_SECRET_EXPIRES: process.env.JWT_SECRET_EXPIRES,
  JWT_REFRESH_SECRET_KEY: process.env.JWT_REFRESH_SECRET_KEY,
  JWT_REFRESH_SECRET_EXPIRES: process.env.JWT_REFRESH_SECRET_EXPIRES,

  //   PASSPORT
  PASSPORT_SESSION_SECRET: process.env.PASSPORT_SESSION_SECRET,
  PASSPORT_REDIRECT_SUCCESS: process.env.PASSPORT_REDIRECT_SUCCESS,
  PASSPORT_REDIRECT_FAILED: process.env.PASSPORT_REDIRECT_FAILED,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,

  //   EMAIL
  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,

  //   URL
  URL_CLIENT: process.env.URL_CLIENT,

  //   PORT
  PORT: process.env.PORT,
  PORT_SOCKET: process.env.PORT_SOCKET,

  //   NODE_ENV
  NODE_ENV: process.env.NODE_ENV,

  IS_PRODUCTION: process.env.NODE_ENV === "production",
};

export default ENV_CONFIG;
