POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "name":"Trung Nghia",
    "email":"tr.trungnghia2001@gmail.com",
    "password":"Nghi@123456",
    "confirm_password":"Nghi@123456"
}

###
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
    "email":"tr.trungnghia2001@gmail.com",
    "password":"Nghi@123456"
}

###
POST http://localhost:5000/api/v1/auth/signout
Content-Type: application/json

###
GET http://localhost:5000/api/v1/auth/get-me
Content-Type: application/json

###
PUT http://localhost:5000/api/v1/auth/update-me
Content-Type: application/json

{
    "phoneNumber": "0123456789",
    "address": "Hai Phong, Viet Nam"
}

###
PUT http://localhost:5000/api/v1/auth/change-password
Content-Type: application/json

{
    "password":"Nghi@1234567",
    "confirm_password":"Nghi@1234567"
}

###
POST http://localhost:5000/api/v1/auth/refresh-token
Content-Type: application/json

###
POST http://localhost:5000/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email":"tr.trungnghia2001@gmail.com"
}

###
POST http://localhost:5000/api/v1/auth/reset-password
Content-Type: application/json

{
    "token":"",
    "password":"123456",
    "confirm_password":"123456"
}