POST http://localhost:5000/api/v1/chat/room/create
Content-Type: application/json

{
    "name":"John Smith",
    "email":"tr.trungnghia2001@gmail.com",
    "password":"Nghi@123456",
    "confirm_password":"Nghi@123456"
}

###